version: "3.8"
services:
  payments-db:
    image: postgres:15.0-alpine
    container_name: payments-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  payment-service:
    image: sivaprasadreddy/payment-service-go
    container_name: payment-service
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - payments-db
    environment:
      APP_PORT: 8082
      APP_DB_HOST: payments-db
      APP_DB_PORT: 5432
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_NAME: postgres
      APP_DB_RUN_MIGRATIONS: "true"
      APP_DB_MIGRATIONS_LOCATION: "file:///internal/database/migrations"